[id="proc_retrieving-topology-specific-service-configuration_{context}"]

= Retrieving topology-specific service configuration

Before you migrate your databases to the {rhos_long} control plane, retrieve the topology-specific service configuration from your {rhos_prev_long} ({OpenStackShort}) environment. You need this configuration for the following reasons:

* To check your current database for inaccuracies
* To ensure that you have the data you need before the migration
* To compare your {OpenStackShort} database with the adopted {rhos_acro} database

Get the controller VIP, to use it later in the environment variable SOURCE_MARIADB_IP.

* In the *allinone host*, get the internal_api VIP from this file:
+
[source,bash,subs=attributes]
----
[cloud-user@allinone ~]cat /home/cloud-user/deployed_network.yaml

[...]
  VipPortMap:
    storage:
      ip_address: 172.18.0.16
      ip_address_uri: 172.18.0.16
      ip_subnet: 172.18.0.16/24
    storage_mgmt:
      ip_address: 172.20.0.16
      ip_address_uri: 172.20.0.16
      ip_subnet: 172.20.0.16/24
    internal_api:
      ip_address: 172.17.0.16
      ip_address_uri: 172.17.0.16
      ip_subnet: 172.17.0.16/24
    # tenant:
    #   ip_address: 172.19.0.2
    #   ip_address_uri: 172.19.0.2
    #   ip_subnet: 172.19.0.2/24
    external:
      ip_address: 172.21.0.16
      ip_address_uri: 172.21.0.16
      ip_subnet: 172.21.0.16/24
[...]
----
+
SOURCE_MARIADB_IP is then 172.17.0.16
+
In the *bastion host*, copy the overcloud-passwords from the all-in-one node to the bastion node:
+
[source,bash,role=execute,subs=attributes]
----
scp -i /home/lab-user/.ssh/{guid}key.pem cloud-user@allinone:/home/cloud-user/tripleo-standalone-passwords.yaml ~/.
----
+
.Prerequisites

* In the *bastion host*. Define the following shell variables. Replace the example values with values that are correct for your environment:
+
[source,bash,role=execute,subs=attributes]
----
ifeval::["{OpenStackPreviousInstaller}" != "director_operator"]
ifeval::["{build}" != "downstream"]
CONTROLLER1_SSH="ssh -i ~/install_yamls/out/edpm/ansibleee-ssh-key-id_rsa root@192.168.122.100"
MARIADB_IMAGE=quay.io/podified-antelope-centos9/openstack-mariadb:current-podified
endif::[]
ifeval::["{build}" == "downstream"]
CONTROLLER1_SSH="ssh -i /home/lab-user/.ssh/{guid}key.pem cloud-user@allinone"
MARIADB_IMAGE=registry.redhat.io/rhoso/openstack-mariadb-rhel9:18.0
endif::[]
SOURCE_MARIADB_IP=172.17.0.16
ifeval::["{build}" != "downstream"]
SOURCE_DB_ROOT_PASSWORD=$(cat ~/tripleo-standalone-passwords.yaml | grep ' MysqlRootPassword:' | awk -F ': ' '{ print $2; }')
endif::[]
ifeval::["{build}" == "downstream"]
SOURCE_DB_ROOT_PASSWORD=$(cat ~/tripleo-standalone-passwords.yaml | grep ' MysqlRootPassword:' | awk -F ': ' '{ print $2; }')
endif::[]
MARIADB_CLIENT_ANNOTATIONS='--annotations=k8s.v1.cni.cncf.io/networks=internalapi'
----

.Procedure

. Export the shell variables for the following outputs and test the connection to the {OpenStackShort} database:
+
[source,bash,role=execute,subs=attributes]
----
ifeval::["{OpenStackPreviousInstaller}" != "director_operator"]
export PULL_OPENSTACK_CONFIGURATION_DATABASES=$(oc run mariadb-client ${MARIADB_CLIENT_ANNOTATIONS} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
endif::[]
ifeval::["{OpenStackPreviousInstaller}" == "director_operator"]
export PULL_OPENSTACK_CONFIGURATION_DATABASES=$(oc run mariadb-client --overrides="$RUN_OVERRIDES" -n $OSPDO_NAMESPACE -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
endif::[]
    mysql -rsh "$SOURCE_MARIADB_IP" -uroot -p"$SOURCE_DB_ROOT_PASSWORD" -e 'SHOW databases;')
echo "$PULL_OPENSTACK_CONFIGURATION_DATABASES"
----
ifeval::["{OpenStackPreviousInstaller}" == "director_operator"]
----
export CONTROLLER1_SSH="oc -n $OSPDO_NAMESPACE rsh -c openstackclient openstackclient ssh controller-0.ctlplane"
----
* With OSPdO, the `mariadb-client` needs to run on the same {rhocp_long} node where the {OpenStackShort} Controller node is running. In addition, the `internalapi-static` network needs to be attached to the pod.
----
export PASSWORD_FILE="tripleo-passwords.yaml"
export OSPDO_NAMESPACE="openstack"
----
. Get the passwords file:
+
[source,bash,role=execute,subs=attributes]
----
oc get secret tripleo-passwords -n $OSPDO_NAMESPACE -o json | jq -r '.data["tripleo-overcloud-passwords.yaml"]' |
base64 -d >"${PASSWORD_FILE}"
----

. Get the name of the {OpenShiftShort} node where the {OpenStackShort} Controller virtual machine is running:
+
[source,bash,role=execute,subs=attributes]
----
export CONTROLLER_NODE=$(oc get vmi -ojson | jq -r '.items[0].status.nodeName')
export SOURCE_OVN_OVSDB_IP=172.17.0.160 # get this from the source OVN DB

export SOURCE_DB_ROOT_PASSWORD=$(grep <"${PASSWORD_FILE}" ' MysqlRootPassword:' | awk -F ': ' '{ print $2; }') || {
    echo "Failed to get the source DB root password"
    exit 1
}
----
. Find the mysql service IP in the `ctlplane-export.yaml` section of the `tripleo-exports-default` ConfigMap:
+
[source,bash,role=execute,subs=attributes]
----
cpexport=$(oc -n "${OSPDO_NAMESPACE}" get cm tripleo-exports-default -o json | jq -r '.data["ctlplane-export.yaml"]')
export SOURCE_MARIADB_IP=$(echo "$cpexport" | sed -e '0,/ MysqlInternal/d' | sed -n '0,/host_nobrackets/s/^.*host_nobrackets\:\s*\(.*\)$/\1/p')
+
export MARIADB_IMAGE='quay.io/podified-antelope-centos9/openstack-mariadb:current-podified'
+
RUN_OVERRIDES='{
    "apiVersion": "v1",
    "metadata": {
        "annotations": {
            "k8s.v1.cni.cncf.io/networks": "[{\"name\": \"internalapi-static\",\"namespace\": \"openstack\", \"ips\":[\"172.17.0.99/24\"]}]"
        }
    },
    "spec": {
        "nodeName": "'"$CONTROLLER_NODE"'",
        "securityContext": {
            "allowPrivilegeEscalation": false,
            "capabilities": {
                "drop": ["ALL"]
            },
            "runAsNonRoot": true,
            "seccompProfile": {
                "type": "RuntimeDefault"
            }
        }
    }
}'
----
.Procedure

. Export the shell variables for the following outputs and test the connection to the {OpenStackShort} database:
+
[source,bash,role=execute,subs=attributes]
----
export PULL_OPENSTACK_CONFIGURATION_DATABASES="$(oc run mariadb-client -q --image "${MARIADB_IMAGE}" \
        -i --rm --restart=Never {pod_annotations} -- mysql -rsh "$SOURCE_MARIADB_IP" -uroot -p"$SOURCE_DB_ROOT_PASSWORD" -e 'SHOW databases;')"
----
endif::[]
+
[NOTE]
The `nova`, `nova_api`, and `nova_cell0` databases are included in the same database host.

. Run `mysqlcheck` on the {OpenStackShort} database to check for inaccuracies:
+
[source,bash,role=execute,subs=attributes]
----
ifeval::["{OpenStackPreviousInstaller}" != "director_operator"]
export PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK=$(oc run mariadb-client ${MARIADB_CLIENT_ANNOTATIONS} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
endif::[]
ifeval::["{OpenStackPreviousInstaller}" == "director_operator"]
export PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK=$(oc run mariadb-client --overrides="$RUN_OVERRIDES" -n $OSPDO_NAMESPACE -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
endif::[]
    mysqlcheck --all-databases -h $SOURCE_MARIADB_IP -u root -p"$SOURCE_DB_ROOT_PASSWORD" | grep -v OK)
echo "$PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK"
----

. Get the {compute_service_first_ref} cell mappings:
+
[source,bash,role=execute,subs=attributes]
----
ifeval::["{OpenStackPreviousInstaller}" != "director_operator"]
export PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS=$(oc run mariadb-client ${MARIADB_CLIENT_ANNOTATIONS} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
endif::[]
ifeval::["{OpenStackPreviousInstaller}" == "director_operator"]
export PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS=$(oc run mariadb-client --overrides="$RUN_OVERRIDES" -n $OSPDO_NAMESPACE -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
endif::[]
    mysql -rsh "${SOURCE_MARIADB_IP}" -uroot -p"${SOURCE_DB_ROOT_PASSWORD}" nova_api -e \
    'select uuid,name,transport_url,database_connection,disabled from cell_mappings;')
echo "$PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS"
----

. Get the hostnames of the registered Compute services:
+
[source,bash,role=execute,subs=attributes]
----
ifeval::["{OpenStackPreviousInstaller}" != "director_operator"]
export PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES=$(oc run mariadb-client ${MARIADB_CLIENT_ANNOTATIONS} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
endif::[]
ifeval::["{OpenStackPreviousInstaller}" == "director_operator"]
export PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES=$(oc run mariadb-client --overrides="$RUN_OVERRIDES" -n $OSPDO_NAMESPACE -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
endif::[]
    mysql -rsh "$SOURCE_MARIADB_IP" -uroot -p"$SOURCE_DB_ROOT_PASSWORD" nova_api -e \
    "select host from nova.services where services.binary='nova-compute' and deleted=0;")
echo "$PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES"
----

. Get the list of the mapped {compute_service} cells:
+
[source,bash,role=execute,subs=attributes]
----
export PULL_OPENSTACK_CONFIGURATION_NOVAMANAGE_CELL_MAPPINGS=$($CONTROLLER1_SSH sudo podman exec -it nova_api nova-manage cell_v2 list_cells)
echo "$PULL_OPENSTACK_CONFIGURATION_NOVAMANAGE_CELL_MAPPINGS"
----
+
[IMPORTANT]
After the {OpenStackShort} control plane services are shut down, if any of the exported values are lost, re-running the command fails because the control plane services are no longer running on the source cloud, and the data cannot be retrieved. To avoid data loss, preserve the exported values in an environment file before shutting down the control plane services.

. Store the exported variables for future use:
+
[source,bash,role=execute,subs=attributes]
----
cat >~/.source_cloud_exported_variables << EOF
PULL_OPENSTACK_CONFIGURATION_DATABASES="$PULL_OPENSTACK_CONFIGURATION_DATABASES"
PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK="$PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK"
PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS="$PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS"
PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES="$PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES"
PULL_OPENSTACK_CONFIGURATION_NOVAMANAGE_CELL_MAPPINGS="$PULL_OPENSTACK_CONFIGURATION_NOVAMANAGE_CELL_MAPPINGS"
SRIOV_AGENTS="$SRIOV_AGENTS"
EOF
----
