= Upgrade a RHOSP 17.1 to RHOSO 18 using the adoption mechanism

include::adoption-attributes.adoc[]

Adoption is the process of migrating a {rhos_prev_long} ({OpenStackShort}) {rhos_prev_ver} overcloud to a {rhos_long_noacro} {rhos_curr_ver} data plane. To ensure that you understand the entire adoption process and how to sufficiently prepare your {OpenStackShort} environment, review the prerequisites, adoption process, and post-adoption tasks.

In this lab, you will use the following infrastructure:

* A 3 OCP controller/workers combo nodes 4.16 OCP cluster
* A bastion host to access to the OCP environment
* A RHEL 9.4 virtualised compute host

Pre-requisites before adoption process:

* xref:install-rhosp-17.1.adoc[Install RHOSP 17.1]
* xref:prereqs.adoc[Perform Prerequisite Operations in the OpenShift cluster]
* xref:install-operators.adoc[Install the Red Hat OpenStack Platform Service Operators]
* xref:network-isolation.adoc[Prepare OCP for OpenStack Network Isolation]

Adoption process:

* xref:migrating-databases.adoc[Migrating DBs]
* xref:adoption-cp.adoc[Control plane Adoption]

In the dataplane adoption you have 2 choices:

* xref:adoption-dp.adoc[Data plane Adoption]
* xref:adoption-dp-recovery.adoc[Data plane Adoption showing how to recover a failure during the adoption of a Compute Node]

Finally, after the update you can add an additional compute node:
* xref:add-additional-compute.adoc[Add additional compute Node after adoption]

Within the lab environment, you will be able to copy and paste the specified commands into the CLI.
For some steps you may also need to edit some of the commands from the  instructions.

*Be sure to review all commands carefully both for functionality and syntax!*