= Upgrade a RHOSP 17.1 to RHOSO 18 using the adoption mechanism

include::adoption-attributes.adoc[]

Adoption is the process of migrating a {rhos_prev_long} ({OpenStackShort}) {rhos_prev_ver} overcloud to a {rhos_long_noacro} {rhos_curr_ver} data plane. To ensure that you understand the entire adoption process and how to sufficiently prepare your {OpenStackShort} environment, review the prerequisites, adoption process, and post-adoption tasks.

In this lab, you will use the following infrastructure:

* A 3 OCP controller/workers combo nodes 4.16 OCP cluster
* A bastion host to access to the OCP environment
* 2 RHEL 9.2 virtualised compute host to install RHOSP 17.1
* A NFS server that needs to be configured
* A RHEL 9.4 virtualised compute host to be added optionally to the the upgraded RHOSO 18.0

Pre-requisites before adoption process:

* Install RHOSP 17.1
* Perform Prerequisite Operations in the OpenShift cluster
* Install the Red Hat OpenStack Platform Service Operators
* Prepare OCP for OpenStack Network Isolation

Adoption process:

* Migrating DBs
* xControl plane Adoption

In the dataplane adoption you have 2 choices:

* Data plane Adoption
* Data plane Adoption showing how to recover a failure during the adoption of a Compute Node

Finally, after the update you can add an additional compute node:

* Add additional compute Node after adoption

Within the lab environment, you will be able to copy and paste the specified commands into the CLI.
For some steps you may also need to edit some of the commands from the  instructions.

*Be sure to review all commands carefully both for functionality and syntax!*