---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: preprovisioned-nodeset
  namespace: openstack
spec:
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
  networkAttachments:
    - ctlplane
  preProvisioned: true
  services:
    - redhat
    - download-cache
    - bootstrap
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - ssh-known-hosts
    - run-os
    - reboot-os
    - install-certs
    - ovn
    - neutron-metadata
    - libvirt
    - nova
    - telemetry
  nodeTemplate:
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    extraMounts:
      - extraVolType: Logs
        volumes:
          - name: ansible-logs
            persistentVolumeClaim:
              claimName: openstack-dataplane-ansible-log
        mounts:
          - name: ansible-logs
            mountPath: "/runner/artifacts"
    managementNetwork: ctlplane
    ansible:
      ansibleUser: cloud-user
      ansiblePort: 22
      ansibleVarsFrom:
        - secretRef:
            name: subscription-manager
        - secretRef:
            name: redhat-registry
      ansibleVars:
        rhc_release: 9.4
        rhc_repositories:
          - {name: "*", state: disabled}
          - {name: "rhel-9-for-x86_64-baseos-eus-rpms", state: enabled}
          - {name: "rhel-9-for-x86_64-appstream-eus-rpms", state: enabled}
          - {name: "rhel-9-for-x86_64-highavailability-eus-rpms", state: enabled}
          - {name: "fast-datapath-for-rhel-9-x86_64-rpms", state: enabled}
          - {name: "rhoso-18.0-for-rhel-9-x86_64-rpms", state: enabled}
          - {name: "rhceph-7-tools-for-rhel-9-x86_64-rpms", state: enabled}
        edpm_bootstrap_release_version_package: []
        neutron_physical_bridge_name: br-ex
        neutron_public_interface_name: eth0
        edpm_network_config_hide_sensitive_logs: false
        edpm_ovn_bridge_mappings: ["datacentre:br-ex"]
        dns_search_domains: sandbox-UUID-ocp4-cluster.svc.cluster.local
        ctlplane_host_routes: []
        ctlplane_subnet_cidr: 24
        ctlplane_mtu: 1500
        external_mtu: 1500
        external_cidr: '24'
        external_host_routes: []
        internalapi_mtu: 1500
        internalapi_cidr: '24'
        internalapi_host_routes: []
        storage_mtu: 1500
        storage_cidr: '24'
        storage_host_routes: []
        tenant_mtu: 1500
        tenant_cidr: '24'
        tenant_host_routes: []
        # edpm_nodes_validation
        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_nodes_validation_validate_gateway_icmp: false
        gather_facts: false
        enable_debug: false
        edpm_network_config_template: |
          ---
          {% set mtu_list = [ctlplane_mtu] %}
          {% for network in nodeset_networks %}
          {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
          {%- endfor %}
          {% set min_viable_mtu = mtu_list | max %}
          network_config:
          - type: interface
            name: eth1
            mtu: {{ ctlplane_mtu }}
            dns_servers: {{ ctlplane_dns_nameservers }}
            domain: {{ dns_search_domains }}
            use_dhcp: false
            addresses:
              - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
          - type: interface
            name: eth2
            mtu: {{ internalapi_mtu }}
            use_dhcp: false
            addresses:
              - ip_netmask: {{ internalapi_ip }}/{{ internalapi_cidr }}
            routes: {{ internalapi_host_routes }}
          - type: interface
            name: eth3
            mtu: {{ min_viable_mtu }}
            use_dhcp: false
            addresses:
              - ip_netmask: {{ storage_ip }}/{{ storage_cidr }}
            routes: {{ storage_host_routes }}
          - type: interface
            name: eth4
            mtu: {{ tenant_mtu }}
            use_dhcp: false
            addresses:
              - ip_netmask: {{ tenant_ip }}/{{ tenant_cidr }}
            routes: {{ tenant_host_routes }}
          - type: ovs_bridge
            name: br-ex
            mtu: 1500
            use_dhcp: false
            addresses:
              - ip_netmask: {{ external_ip }}/{{ external_cidr }}
            members:
              - type: interface
                name: eth5
                mtu: 1500
                primary: true
  nodes: {}
