= Creating the RHOSO Control Plane Base Configuration

== Creating the initial overlay

Change directory to your base forked gitops repo, in your bastion:

[source,bash,role=execute]
----
cd /home/lab-user/labrepo/content/files/manifests
----

Create the environment/base directory
----
mkdir -p environments/base
----

[source,bash,role=execute]
----
cat > environments/base/kustomization.yaml <<EOF
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - https://github.com/openstack-gitops/rhoso-gitops/base/initialize/gitops/components/annotations?ref=main

resources:
  - https://github.com/rh-osp-demo/showroom_osp-on-ocp-day2/content/files/manifests/base?ref=main
EOF
----

Validate the base configuration can be generated with *kustomize build*:
[source,bash,role=execute]
----
kustomize build environments/base
----

== Creating the Environment Overlay

=== Configuring OpenShift Networking for RHOS

==== Creating the environment overlay configuration

Create an environment directory to store the managed cluster overlay configuration:

[source,bash,role=execute]
----
mkdir -p environments/shift1
----

Create the *kustomization.yaml* for the shift1 environment overlay configuration:

[source,bash,role=execute]
----
cat > environments/shift1/kustomization.yaml <<EOF
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
EOF
----

Validate the base configuration can be generated with *kustomize build*:
[source,bash,role=execute]
----
kustomize build environments/shift1
----

==== Patching the NodeNetworkConfigurationPolicy

Update the NodeNetworkConfigurationPolicy manifests in our base configuration, including updating the nodeSelector hostname. For more information about the NodeNetworkConfigurationPolicy manifest and retrieving the OpenShift worker nodes, see
Use the information provided by the procedure in the Preparing RHOCP with isolated network interfaces guide for the patches being added to the kustomization.yaml configuration.
In our worked example, all changes will be applied to the environments/shift1/kustomization.yaml file unless stated otherwise.

Create a kustomization patch to update the nodeSelector hostnames and NodeNetworkConfigurationPolicy object name:

Edit the *kustomization.yaml* created in the previous step:

[source,bash,role=execute]
----
vim environments/shift1/kustomization.yaml
----

And add the patches, for example to match nnpc of every worker to the the hostname of our cluster: 

[source,bash,subs=attributes]
----
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      group: nmstate.io
      version: v1
      kind: NodeNetworkConfigurationPolicy
      name: osp-multi-nic-worker-ocp4-worker1
    patch: |-
      - op: replace
        path: /metadata/name
        value: "control-plane-cluster-{guid}-1"
      - op: replace
        path: /spec/nodeSelector/kubernetes.io~1hostname
        value: "control-plane-cluster-{guid}-1"

  - target:
      group: nmstate.io
      version: v1
      kind: NodeNetworkConfigurationPolicy
      name: osp-multi-nic-worker-ocp4-worker2
    patch: |-
      - op: replace
        path: /metadata/name
        value: "control-plane-cluster-{guid}-2"
      - op: replace
        path: /spec/nodeSelector/kubernetes.io~1hostname
        value: "control-plane-cluster-{guid}-2"

  - target:
      group: nmstate.io
      version: v1
      kind: NodeNetworkConfigurationPolicy
      name: osp-multi-nic-worker-ocp4-worker3
    patch: |-
      - op: replace
        path: /metadata/name
        value: "control-plane-cluster-{guid}-3"
      - op: replace
        path: /spec/nodeSelector/kubernetes.io~1hostname
        value: "control-plane-cluster-{guid}-3"

----

Validate the base configuration can be generated with *kustomize build*:
[source,bash,role=execute]
----
kustomize build environments/shift1
----

Commit the files created and push it to your github repo:
[source,bash,role=execute]
----
git add .
git commit -m "Base and shift1 environment"
git push origin
----


== Deploying the overlay using a GitOps Application

Deploy the RHOSO control plane using a GitOps Application which will be deployed using sync-waves, resulting in the automated deployment of the environment on OpenShift.

Make a directory to hold the Application manifest:

[source,bash,role=execute]
----
mkdir -p applications/rhoso
----

Create the Application manifest:

[source,bash,role=execute]
----
cat > applications/rhoso/application-environment-shift1.yaml <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: environment-rhoso-shift1
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: content/files/manifests/environments/shift1
    repoURL: https://github.com/$your_github_id/showroom_osp-on-ocp-day2.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
EOF
----

Deploy the RHOSO control plane with the GitOps Application:

[source,bash,role=execute]
----
oc create --save-config -f applications/rhoso/application-environment-shift1.yaml
----

Wait for the Application to deploy successfully:

[source,bash,role=execute]
----
oc wait --timeout=600s -nopenshift-gitops applications.argoproj.io/environment-rhoso-shift1 --for jsonpath='{.status.health.status}'=Healthy
----

Wait for the Application to deploy successfully:

[source,bash,role=execute]
----
oc get -n openshift-gitops application.argoproj.io environment-rhoso-shift1
----