# Install and discover RHOSO using Gitops ArgoCD

Welcome to the Red Hat OpenStack Services on OpenShift (RHOSO) lab instructions.
These instructions will guide you through the installation of the next generation of Red Hat's OpenStack product onto an existing OpenShift Cluster utilizing a bastion host and a single host for the data plane.

In this lab, you will use the following infrastructure:

* A 3 OCP controller/worker 4.16 OCP cluster
* A bastion host to access to the OCP environment
* A RHEL 9.4 virtualised compute host

In this lab, you will cover the following topics:

* xref:prereqs-gitops.adoc[Install the Operators prerequisites using OpenShift gitops]
* xref:install-operators-gitops.adoc[Install the Red Hat OpenStack Platform Service Operators using OpenShift gitops]
* xref:secure.adoc[Configure Secure Access for OpenStack Services]
* xref:install-nfs-server.adoc[Install NFS server]
* xref:deploy-control-plane-gitops.adoc[Deploy RHOSO control plane using OpenShift gitops]
* xref:deploy-data-plane-gitops.adoc[Deploy RHOSO data plane using OpenShift gitops]
* xref:access-gitops.adoc[Access OpenStack]

Within the lab environment, you will be able to copy and paste the specified commands into the CLI.
For some steps you may also need to edit some of the commands from the  instructions.

== Fork the Lab Repository

Fork the GitHub repository into your personal GitHub space:

https://github.com/rh-osp-demo/showroom_osp-on-ocp-day2

== Add the Bastion SSH Key to the SSH Agent

[source,bash,subs=attributes]
----
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/{guid}key.pem
----

== Add the SSH Public Key to GitHub

Copy the public key `~/.ssh/{guid}key.pub` from the bastion to your GitHub account:

1. Copy the SSH public key to your clipboard.
2. In the upper-right corner of any page on GitHub, click your profile photo, then click *Settings*.
3. In the "Access" section of the sidebar, click *SSH and GPG keys*.
4. Click *New SSH key* or *Add SSH key*.
5. In the *Title* field, add a descriptive label, such as `"bastion RHOSO gitops key"`.
6. Click *Add SSH key*.

== Set Your Repository URL

In the next chapter, we will refer to your forked repository using the variable: `$YOUR_REPO_URL`.

Example:

During the lab, replace `$YOUR_REPO_URL` with: 'https://github.com/$your_github_id/showroom_osp-on-ocp-day2.git'

== Clone Your Forked Repository

In the bastion, clone your forked repository to the bastion using SSH:

[source,bash]
----
cd
git clone git@github.com:$your_github_id/showroom_osp-on-ocp-day2.git labrepo
cd labrepo
----

*Be sure to review all commands carefully for both functionality and syntax!*
